version: '3'

# This file extends docker-compose-mediators.yml

services:
  mediator:
    environment:
      NGROK_NAME: mediator-ngrok
    entrypoint: ./scripts/ngrok-wait.sh
    depends_on: [mediator-ngrok]

  mediator-ngrok:
    image: wernight/ngrok
    command: ngrok http -bind-tls=true --log stdout mediator:3001
    networks:
      - hyperledger

networks:
  hyperledger:
