version: '3'

services:
  mediator:
    build: ..
    image: aries-framework-javascript
    container_name: afj-mediator
    command: yarn run-mediator
    platform: linux/amd64
    networks:
      - hyperledger
    ports:
      - 3001:3001

networks:
  hyperledger:
