version: '3'

services:
  mediator:
    build: ..
    image: credo
    container_name: credo-mediator
    command: yarn run-mediator
    platform: linux/amd64
    networks:
      - hyperledger
    ports:
      - 3001:3001

networks:
  hyperledger:
