# Repositories have 10 GB of cache storage per repository
# Documentation: https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#usage-limits-and-eviction-policy
name: 'Cleanup - Cache'
on:
  schedule:
    - cron: '0 0 * * 0/3'
  workflow_dispatch:

jobs:
  delete-caches:
    name: 'Delete Actions caches'
    runs-on: ubuntu-latest

    steps:
      - name: 'Wipe Github Actions cache'
        uses: easimon/wipe-cache@v2
